# Generated by Django 2.2.5 on 2019-09-30 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190930_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Member'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 30, 18, 24, 36, 861171, tzinfo=utc)),
        ),
    ]
